package com.example.waynixgoapp.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.compositionLocalOf

data class WaynixStrings(
    val appName: String,
    val profile: String,
    val home: String,
    val postAd: String,
    val language: String,
    val supportCenter: String,
    val logout: String,
    val settings: String,
    val myAds: String,
    val fromCity: String,
    val toDistrict: String,
    val passenger: String,
    val driver: String,
    val sendSuggestions: String,
    val write: String,
    val areYouSureLogout: String,
    val cancel: String,
    // Add more as needed based on the screens we touch
    val findCompanion: String,
    val fastSearch: String,
    val fastSearchDesc: String,
    val reliableCompanions: String,
    val reliableCompanionsDesc: String,
    val allDistricts: String,
    val allDistrictsDesc: String,
    val loginWithNumber: String,
    val yourNumber: String,
    val enterNumberDesc: String,
    val sendCode: String,
    val confirmCode: String,
    val weSentSms: String,
    val invalidCode: String,
    val whatIsYourName: String,
    val introduceYourself: String,
    val continueBtn: String,
    val resend: String,
    val waitSms: String,
    val testCodeHint: String,
    val examplePhone: String,
    val enterOtp: String,
    val yourRidePublished: String,
    val publish: String,
    val setPrice: String,
    val seatsCount: String,
    val timeLabel: String,
    val commentLabel: String,
    val now: String,
    val later: String,
    val period: String,
    val selectTime: String,
    val done: String,
    val setPhoneInProfile: String,
    val setCorrectPrice: String,
    val adsDrivers: String,
    val noDrivers: String,
    val connectionFailed: String,
    val retry: String,
    // Google linking step
    val linkGoogleTitle: String,
    val linkGoogleDesc: String,
    val continueWithGoogle: String,
    val skipForNow: String,
    val googleLinked: String,
    val googleLinkFailed: String,
    val googleAlreadyLinkedToOther: String,
    val whyLinkGoogle: String,
    val activeAds: String,
    val history: String,
    val emptyHistory: String,
    val noActiveAds: String,
    val finishRide: String,
    val rideFinished: String,
    val selectFromCity: String,
    val selectToDistrict: String
)

val RuStrings = WaynixStrings(
    appName = "WAYNIX GO",
    profile = "Профиль",
    home = "Главная",
    postAd = "Добавить",
    language = "ЯЗЫК",
    supportCenter = "ПОДДЕРЖКА",
    logout = "ВЫЙТИ",
    settings = "НАСТРОЙКИ",
    myAds = "Мои поездки",
    fromCity = "Откуда",
    toDistrict = "Куда",
    passenger = "Пассажир",
    driver = "Водитель",
    sendSuggestions = "Ответим на любые вопросы",
    write = "Написать",
    areYouSureLogout = "Вы уверены, что хотите выйти?",
    cancel = "Отмена",
    findCompanion = "Найди попутчика или водителя",
    fastSearch = "Быстрый поиск",
    fastSearchDesc = "Находи водителей за секунды",
    reliableCompanions = "Надёжные попутчики",
    reliableCompanionsDesc = "Только проверенные пользователи",
    allDistricts = "Все районы",
    allDistrictsDesc = "Каракалпакстан и Нукус",
    loginWithNumber = "Войти по номеру",
    yourNumber = "Ваш номер",
    enterNumberDesc = "Введите номер — мы отправим\nкод подтверждения",
    sendCode = "ОТПРАВИТЬ КОД",
    confirmCode = "ПОДТВЕРДИТЬ",
    weSentSms = "Мы отправили SMS на\n",
    invalidCode = "Неверный код. Попробуйте ещё раз.",
    whatIsYourName = "Как вас зовут?",
    introduceYourself = "Представьтесь, чтобы водители и попутчики\nмогли к вам обращаться",
    continueBtn = "ПРОДОЛЖИТЬ",
    resend = "Отправить повторно",
    waitSms = "SMS-уведомление придёт в течение минуты.",
    testCodeHint = "Для теста введите: 123456",
    examplePhone = "Пример: 90 123 45 67",
    enterOtp = "Код подтверждения",
    yourRidePublished = "Объявление опубликовано!",
    publish = "ОПУБЛИКОВАТЬ",
    setPrice = "ЦЕНА ЗА МЕСТО (СУМ)",
    seatsCount = "КОЛ-ВО ЧЕЛОВЕК",
    timeLabel = "ВРЕМЯ",
    commentLabel = "Дополнительно (комментарий)",
    now = "Сейчас",
    later = "Позже",
    period = "Период",
    selectTime = "Выберите время",
    done = "ГОТОВО",
    setPhoneInProfile = "Укажите номер телефона в профиле",
    setCorrectPrice = "Укажите корректную цену",
    adsDrivers = "ОБЪЯВЛЕНИЯ ВОДИТЕЛЕЙ",
    noDrivers = "НЕТ ВОДИТЕЛЕЙ",
    connectionFailed = "Ошибка подключения к серверу",
    retry = "ПОВТОРИТЬ",
    linkGoogleTitle = "Привяжите Google",
    linkGoogleDesc = "Дополнительная защита аккаунта.\nНомер телефона остаётся основным.",
    continueWithGoogle = "ПРОДОЛЖИТЬ С GOOGLE",
    skipForNow = "Пропустить",
    googleLinked = "Google аккаунт привязан",
    googleLinkFailed = "Не удалось привязать Google. Попробуйте ещё раз.",
    googleAlreadyLinkedToOther = "Этот Google уже привязан к другому номеру.",
    whyLinkGoogle = "Двухфакторная защита: вход возможен только если телефон и Google совпадают.",
    activeAds = "АКТИВНЫЕ",
    history = "ИСТОРИЯ",
    emptyHistory = "ИСТОРИЯ ПУСТА",
    noActiveAds = "НЕТ АКТИВНЫХ ЗАПРОСОВ",
    finishRide = "ЗАВЕРШИТЬ ПОЕЗДКУ",
    rideFinished = "ПОЕЗДКА ЗАВЕРШЕНА",
    selectFromCity = "Выберите пункт отправления",
    selectToDistrict = "Выберите пункт назначения"
)

val UzStrings = WaynixStrings(
    appName = "WAYNIX GO",
    profile = "Profil",
    home = "Asosiy",
    postAd = "Qo'shish",
    language = "TIL",
    supportCenter = "QO'LLAB-QUVVATLASH",
    logout = "CHIQISH",
    settings = "SOZLAMALAR",
    myAds = "Mening safarlarim",
    fromCity = "Qayerdan",
    toDistrict = "Qayerga",
    passenger = "Yo'lovchi",
    driver = "Haydovchi",
    sendSuggestions = "Takliflaringizni yuboring",
    write = "Yozish",
    areYouSureLogout = "Haqiqatan ham chiqib ketmoqchimisiz?",
    cancel = "Bekor qilish",
    findCompanion = "Hamroh yoki haydovchi toping",
    fastSearch = "Tezkor qidiruv",
    fastSearchDesc = "Haydovchilarni soniyalarda toping",
    reliableCompanions = "Ishonchli hamrohlar",
    reliableCompanionsDesc = "Faqat tasdiqlangan foydalanuvchilar",
    allDistricts = "Barcha tumanlar",
    allDistrictsDesc = "Qoraqalpog'iston va Nukus",
    loginWithNumber = "Raqam orqali kirish",
    yourNumber = "Sizning raqamingiz",
    enterNumberDesc = "Raqamingizni kiriting — biz tasdiqlash\nkodini yuboramiz",
    sendCode = "KODNI YUBORISH",
    confirmCode = "TASDIQLASH",
    weSentSms = "SMS yubordik\n",
    invalidCode = "Noto'g'ri kod. Yana urinib ko'ring.",
    whatIsYourName = "Ismingiz nima?",
    introduceYourself = "Haydovchi va hamrohlar ishib bilishi uchun\no'zingizni tanishtiring",
    continueBtn = "DAVOM ETISH",
    resend = "Qayta yuborish",
    waitSms = "SMS-xabar bir daqiqa ichida yetib keladi.",
    testCodeHint = "Test uchun kiriting: 123456",
    examplePhone = "Misol: 90 123 45 67",
    enterOtp = "Tasdiqlash kodi",
    yourRidePublished = "E'lon muvaffaqiyatli joylandi!",
    publish = "JOYLASHTIRISH",
    setPrice = "JOI NARXI (SO'M)",
    seatsCount = "ODAMLAR SONI",
    timeLabel = "VAQT",
    commentLabel = "Qo'shimcha (izoh)",
    now = "Hozir",
    later = "Keyinroq",
    period = "Davr",
    selectTime = "Vaqtni tanlang",
    done = "TAYYOR",
    setPhoneInProfile = "Profil sahifasida telefon raqamini ko'rsating",
    setCorrectPrice = "To'g'ri narxni kiriting",
    adsDrivers = "HAYDOVCHILAR E'LONLARI",
    noDrivers = "HAYDOVCHILAR YO'Q",
    connectionFailed = "Server bilan aloqa uzildi",
    retry = "QAYTA URINISH",
    linkGoogleTitle = "Google'ni bog'lang",
    linkGoogleDesc = "Hisobni qo'shimcha himoya.\nTelefon raqami asosiy bo'lib qoladi.",
    continueWithGoogle = "GOOGLE BILAN DAVOM ETISH",
    skipForNow = "O'tkazib yuborish",
    googleLinked = "Google hisob bog'landi",
    googleLinkFailed = "Google'ni bog'lab bo'lmadi. Qayta urinib ko'ring.",
    googleAlreadyLinkedToOther = "Bu Google boshqa raqamga bog'langan.",
    whyLinkGoogle = "Ikki faktorli himoya: kirish uchun telefon va Google mos kelishi shart.",
    activeAds = "FAOL",
    history = "TARIX",
    emptyHistory = "TARIX BO'SH",
    noActiveAds = "FAOL SO'ROVLAR YO'Q",
    finishRide = "SAFARNI YAKUNLASH",
    rideFinished = "SAFAR YAKUNLANDI",
    selectFromCity = "Jo'nash joyini tanlang",
    selectToDistrict = "Borish joyini tanlang"
)

val LocalWaynixStrings = compositionLocalOf { RuStrings }

@Composable
fun ProvideWaynixStrings(languageCode: String, content: @Composable () -> Unit) {
    val strings = when (languageCode.uppercase()) {
        "UZ" -> UzStrings
        else -> RuStrings
    }
    CompositionLocalProvider(LocalWaynixStrings provides strings) {
        content()
    }
}
