# Generated by Django 6.0.5 on 2026-06-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_remove_driver_telegram_username_driver_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideoffer',
            name='seats_available',
        ),
        migrations.AddField(
            model_name='rideoffer',
            name='total_seats',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Всего мест'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено (Место занято)'), ('rejected', 'Отклонено водителем'), ('cancelled', 'Отменено пассажиром'), ('checked_in', 'Пассажир сел в машину'), ('no_show', 'Пассажир не пришел (Место освободилось)')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rideoffer',
            name='route_description',
            field=models.TextField(blank=True, verbose_name='Описание маршрута'),
        ),
        migrations.AlterField(
            model_name='rideoffer',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('done', 'Завершено'), ('cancelled', 'Отменено')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
